public let AEROSPACE_WINDOW_ID = "AEROSPACE_WINDOW_ID"
public let AEROSPACE_WORKSPACE = "AEROSPACE_WORKSPACE"
public let AEROSPACE_FOCUSED_WORKSPACE = "AEROSPACE_FOCUSED_WORKSPACE"
public let AEROSPACE_PREV_WORKSPACE = "AEROSPACE_PREV_WORKSPACE"
