#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help --ignore-shell-parser
swift build "$@"
swift build --target AppBundleTests "$@" || true # swift build doesn't build test targets by default :(

rm -rf .debug && mkdir .debug
cp -r .build/debug/airlock .debug
cp -r .build/debug/AirlockApp .debug

# Wrap AirlockApp in a .app bundle so macOS can grant accessibility permissions
APP_BUNDLE=".debug/Airlock-Debug.app"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
cp .debug/AirlockApp "$APP_BUNDLE/Contents/MacOS/AirlockApp"
cat > "$APP_BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>dev.airlock.debug</string>
    <key>CFBundleExecutable</key>
    <string>AirlockApp</string>
    <key>CFBundleName</key>
    <string>Airlock-Debug</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST
