#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

export XCODEGEN_FLIGHTDECK_CODE_SIGN_IDENTITY="${DEVELOPER_ID_APPLICATION:-Developer ID Application: Saad Bash (${FLIGHTDECK_TEAM_ID:-2ZPA772V9V})}"
export XCODEGEN_FLIGHTDECK_DEVELOPMENT_TEAM="${FLIGHTDECK_TEAM_ID:-2ZPA772V9V}"
build_version="0.0.0-SNAPSHOT"
generate_xcodeproj=1
generate_cmd_help=1
generate_shell_parser=1
generate_git_hash=0
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2 ;;
        --codesign-identity) XCODEGEN_FLIGHTDECK_CODE_SIGN_IDENTITY="$2"; shift 2 ;;
        --generate-git-hash) generate_git_hash=1; shift 1;;
        --ignore-cmd-help) generate_cmd_help=0; shift 1 ;;
        --ignore-xcodeproj) generate_xcodeproj=0; shift 1 ;;
        --ignore-shell-parser) generate_shell_parser=0; shift 1 ;;
        *) echo "Unknown option $1"; exit 1 ;;
    esac
done

if test $generate_shell_parser = 1; then
    ./script/generate-shell-parser.sh
fi

if test $generate_cmd_help = 1; then
    node ./script/generate-command-docs.mjs
fi

cat > Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY generate.sh
public let aeroSpaceAppVersion = "$build_version"
EOF

entries() {
    true
}

cat <<EOF > ./Sources/Common/gitHashGenerated.swift
// FILE IS GENERATED BY generate.sh
public let gitHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse HEAD; fi)"
public let gitShortHash = "$(if test $generate_git_hash = 0; then echo "SNAPSHOT"; else git rev-parse --short HEAD; fi)"
EOF

if test $generate_xcodeproj = 1; then
    export XCODEGEN_FLIGHTDECK_VERSION=$build_version
    ./script/install-dep.sh --xcodegen
    ./.deps/xcodegen/xcodegen # https://github.com/yonaskolb/XcodeGen
fi
