# Project configuration. Managed by https://github.com/yonaskolb/XcodeGen

name: AeroSpace

packages:
  HotKey:
    url: https://github.com/soffes/HotKey
    exactVersion: 0.1.3
  TOMLKit:
    url: https://github.com/LebJe/TOMLKit
    exactVersion: 0.5.5
  Socket:
    url: https://github.com/Kitura/BlueSocket
    exactVersion: 2.0.4
  LocalPackage:
    path: LocalPackage
  Nimble:
    url: https://github.com/Quick/Nimble
    exactVersion: 12.0.0

targets:
  AeroSpace:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources: [src/, docs/config-examples/default-config.toml]
    configFiles:
      Release: .local.xcconfig
      Debug: .local.xcconfig
    dependencies:
      - package: HotKey
      - package: TOMLKit
      - package: Socket
      - package: LocalPackage
        products:
          - Common
    settings:
      base:
        SWIFT_VERSION: 5.8
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: ${AEROSPACE_VERSION}
        CURRENT_PROJECT_VERSION: ${AEROSPACE_BUILD_NUMBER}
        SWIFT_OBJC_BRIDGING_HEADER: "src/Bridged-Header.h"
        # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256
        # Specifies whether the app runs as an agent app. If this key is set to YES, Launch Services runs the app as an agent app.
        # Agent apps do not appear in the Dock or in the Force Quit window
        INFOPLIST_KEY_LSUIElement: YES
      configs:
        debug:
          PRODUCT_NAME: AeroSpace-Debug
          PRODUCT_BUNDLE_IDENTIFIER: bobko.debug.aerospace
        release:
          PRODUCT_NAME: AeroSpace
          PRODUCT_BUNDLE_IDENTIFIER: bobko.aerospace
    entitlements:
      path: src/AeroSpace.entitlements
      properties:
        # Accessibility API doesn't work in sandboxed app
        com.apple.security.app-sandbox: false
  AeroSpace-Tests:
    type: bundle.unit-test
    platform: macOS
    sources: [test/]
    scheme:
      testTargets:
        - AeroSpace-Tests
      gatherCoverageData: true
    dependencies:
      - target: AeroSpace
      - package: Nimble
    settings:
      base:
        SWIFT_VERSION: 5.8
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/AeroSpace-Debug.app/Contents/MacOS/AeroSpace-Debug"
        GENERATE_INFOPLIST_FILE: YES
