name: New Issue
description: New Issue
body:
  - type: markdown
    attributes:
      value: |
        Unfortunately, AeroSpace project doesn't openly accept Issues. See: https://github.com/nikitabobko/AeroSpace/issues/947
  - type: checkboxes
    id: checkbox
    attributes:
      label: '_'
      options:
        - label: |
            I read https://github.com/nikitabobko/AeroSpace/issues/947
          required: true
