import HotKey

let keysMap: [String: Key] = [
    "a": .a,
    "b": .b,
    "c": .c,
    "d": .d,
    "e": .e,
    "f": .f,
    "g": .g,
    "h": .h,
    "i": .i,
    "j": .j,
    "k": .k,
    "l": .l,
    "m": .m,
    "n": .n,
    "o": .o,
    "p": .p,
    "q": .q,
    "r": .r,
    "s": .s,
    "t": .t,
    "u": .u,
    "v": .v,
    "w": .w,
    "x": .x,
    "y": .y,
    "z": .z,

    "0": .zero,
    "1": .one,
    "2": .two,
    "3": .three,
    "4": .four,
    "5": .five,
    "6": .six,
    "7": .seven,
    "8": .eight,
    "9": .nine,

    "minus": .minus,
    "equal": .equal,
    "period": .period,
    "comma": .comma,
    "slash": .slash,
    "backslash": .backslash,
    "quote": .quote,
    "semicolon": .semicolon,
    "backtick": .grave,
    "leftSquareBracket": .leftBracket,
    "rightSquareBracket": .rightBracket,
    "space": .space,
    "enter": .return,
    "esc": .escape,
    //"delete": .delete, // todo backspace?
    "tab": .tab,

    "left": .leftArrow,
    "down": .downArrow,
    "up": .upArrow,
    "right": .rightArrow,
]

let modifiersMap: [String: NSEvent.ModifierFlags] = [
    "shift": .shift,
    "alt": .option,
    "ctrl": .control,
    "cmd": .command,
    "fn": .function,
]
