#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

zip_uri='' # mandatory
cask_zip_uri=''
cask_name='' # mandatory
build_version="0.0.0-SNAPSHOT"
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        --cask-zip-uri) cask_zip_uri="$2"; shift 2;;
        --cask-name) cask_name="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi
if test -z "$cask_name"; then echo "--cask-name is mandatory" > /dev/stderr; exit 1; fi

case "$cask_name" in
    flightdeck) conflicts_with_casks='conflicts_with cask: "flightdeck-dev"';;
    flightdeck-dev) conflicts_with_casks='conflicts_with cask: "flightdeck"';;
    *) echo "Unknown cask name: $cask_name. Allowed cask names: flightdeck, flightdeck-dev" > /dev/stderr; exit 1;;
esac

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    if test -z "$cask_zip_uri"; then
        cask_zip_uri="file://$(realpath "$zip_file")"
    fi
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/FlightDeck-tmp.zip
    rm -rf $zip_file
    curl -L "$zip_uri" -o $zip_file
    if test -z "$cask_zip_uri"; then
        cask_zip_uri="$zip_uri"
    fi
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest' # Prevent 'Not upgrading aerospace, the latest version is already installed'
zip_root_dir="FlightDeck-v$build_version"
if ! grep -q SNAPSHOT <<< "$build_version"; then
    cask_version="\"$build_version\""
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
    cask_zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$cask_zip_uri")
fi

rm -f ".release/$cask_name.rb" || true
mkdir -p .release
cat > ".release/$cask_name.rb" <<EOF
# frozen_string_literal: true

cask "$cask_name" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$cask_zip_uri"
  name "FlightDeck"
  desc "Tiling window manager inspired by i3"
  homepage "https://github.com/saadjs/FlightDeck"

  $conflicts_with_casks
  depends_on macos: :ventura

  app "$zip_root_dir/FlightDeck.app"
  binary "$zip_root_dir/bin/flightdeck"
  binary "$zip_root_dir/shell-completion/zsh/_flightdeck",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_flightdeck"
  binary "$zip_root_dir/shell-completion/bash/flightdeck",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/flightdeck"
  binary "$zip_root_dir/shell-completion/fish/flightdeck.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/flightdeck.fish"

  Dir["#{staged_path}/$zip_root_dir/manpage/*"].each { |man| manpage man }
end
EOF
