#!/usr/bin/env bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

entries() {
    for file in $(ls docs/aerospace-*.adoc); do
        if grep -q 'exec' <<< $file; then
            continue
        fi
        subcommand=$(basename $file | sed 's/^aerospace-//' | sed 's/\.adoc$//')
        desc="$(grep :manpurpose: $file | sed -E 's/:manpurpose: (.*)/\1/')"
        echo "    [\"  $subcommand\", \"$desc\"],"
    done
}

cat <<EOF > ./LocalPackage/Sources/Cli/subcommandDescriptionsGenerated.swift
// FILE IS GENERATED BY script/generate-command-descriptions.sh
let subcommandDescriptions = [
$(entries)
]
EOF
