= aerospace-move(1)
include::util/man-attributes.adoc[]
// tag::purpose[]
:manpurpose: Move the window in the given direction
// end::purpose[]
:manname: aerospace-move

== Synopsis
// tag::synopsis[]
aerospace move [-h|--help] (left|down|up|right) [floating_pixel]
// end::synopsis[]

== Description

// tag::body[]
{manpurpose}

The optional `floating_pixel` argument specifies how far the window should be moved if it is floating.
The default is 50 pixels

Deprecated name: `move-through`

include::util/conditional-examples-header.adoc[]

. Given this layout
+
----
h_tiles
├── window 1 (focused)
└── window 2
----
+
`move right` will result in the following layout
+
----
h_tiles
├── window 2
└── window 1 (focused)
----

. Given this layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----
+
`move right` will result in the following layout
+
----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----

. Given this layout
+
----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----
+
`move left` will result in the following layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----
. *Implicit container example*
+
In some cases, `move` needs to implicitly create a container to fulfill your command.
+
Given this layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── window 3
----
+
`move up` will result in the following layout
+
----
v_tiles
├── window 2 (focused)
└── h_tiles
    ├── window 1
    └── window 3
----
+
`v_tiles` is an implicitly created container.

// end::body[]

include::util/conditional-options-header.adoc[]

-h, --help:: Print help

include::util/man-footer.adoc[]
