= aerospace-list-monitors(1)
include::util/man-attributes.adoc[]
:manname: aerospace-list-monitors
// tag::purpose[]
:manpurpose: Print monitors that satisfy conditions
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
// tag::synopsis[]
aerospace list-monitors [-h|--help] [--focused [no]] [--mouse [no]] [--format <output-format>]
// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help

--focused [no]::
Filter results to only print the focused monitor.
`[no]` inverts the condition

--mouse [no]::
Filter results to only print the monitor with the mouse.
`[no]` inverts the condition

--format <output-format>:: Specify output format. See "Output Format" section for more details

// =========================================================== Output Format
include::util/conditional-output-format-header.adoc[]

Output format can be configured with optional `[--format <output-format>]` option.
`<output-format>` supports https://en.wikipedia.org/wiki/String_interpolation[string interpolation].

If not specified, the default `<output-format>` is: +
`%{monitor-id}%{right-padding} | %{monitor-name}`

The following variables can be used inside `<output-format>`:

%{monitor-id}:: Number. Sequential number of the belonging monitor
%{monitor-name}:: String. Name of the belonging monitor

%{right-padding}:: A special variable which expands with a minimum number of spaces required to form a right padding in the appropriate column
%{newline}:: Unicode U+000A newline symbol `\n`
%{tab}:: Unicode U+0009 tab symbol `\t`

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
