= aerospace-move(1)
include::util/man-attributes.adoc[]
// tag::purpose[]
:manpurpose: Move the focused window in the given direction
// end::purpose[]
:manname: aerospace-move

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospace move [-h|--help] [--window-id <window-id>] [--focus-follows-window]
               [--fail-if-noop] [--boundaries <boundary>] [--wrap-around] (left|down|up|right)

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
Move the focused window in the given direction. See the "Examples" section for more details.

Deprecated name: `move-through`

// =========================================================== Options
include::./util/conditional-options-header.adoc[]

-h, --help:: Print help
--fail-if-noop:: Exit with a non-zero status if the window cannot move because it’s at the boundary
--wrap-around:: Make it possible to wrap around the movement

--boundaries <boundary>::
Defines move boundaries. +
`<boundary>` possible values: `(workspace|all-monitors-outer-frame)`. +
The default is: `workspace`

--focus-follows-window::
Make sure that the window in question receives focus after moving.
This flag is a shortcut for manually running `aerospace-workspace`/`aerospace-focus` after `move` successful execution.

--window-id <window-id>::
include::./util/window-id-flag-desc.adoc[]

// =========================================================== Examples
include::util/conditional-examples-header.adoc[]

. Given this layout
+
----
h_tiles
├── window 1 (focused)
└── window 2
----
+
`move right` will result in the following layout
+
----
h_tiles
├── window 2
└── window 1 (focused)
----

. Given this layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----
+
`move right` will result in the following layout
+
----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----

. Given this layout
+
----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----
+
`move left` will result in the following layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----
. *Implicit container example*
+
In some cases, `move` needs to implicitly create a container to fulfill your command.
+
Given this layout
+
----
h_tiles
├── window 1
├── window 2 (focused)
└── window 3
----
+
`move up` will result in the following layout
+
----
v_tiles
├── window 2 (focused)
└── h_tiles
    ├── window 1
    └── window 3
----
+
`v_tiles` is an implicitly created container.

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
