= aerospace-focus(1)
include::util/man-attributes.adoc[]
:manname: aerospace-focus
// tag::purpose[]
:manpurpose: Set focus to the nearest window in in the given direction.
// end::purpose[]

== Synopsis
[verse]
// tag::synopsis[]
aerospace focus [-h|--help] [--boundaries <boundary>]
                [--boundaries-action <action>] (left|down|up|right)

// end::synopsis[]

== Description

// tag::body[]
{manpurpose}

Contrary to i3, `focus` command doesn't have a separate argument to focus floating windows.
From `focus` command perspective, floating windows are part of xref:guide.adoc#tree[the tree].
The floating window parent container is determined as the smallest tiling container that contains the center of the floating window.

This technique eliminates the need for an additional binding for floating windows.

`focus child|parent` isn't supported because the necessity of this operation is under the question.
https://github.com/nikitabobko/AeroSpace/issues/5

include::util/conditional-options-header.adoc[]

-h, --help:: Print help

--boundaries <boundary>::
Defines focus boundaries. +
`<boundary>` possible values: `(workspace|all-monitors-outer-frame)`. +
The default is: `workspace`

--boundaries-action <action>::
Defines the behavior when requested to cross the `<boundary>`. +
`<action>` possible values: `(stop|wrap-around-the-workspace|wrap-around-all-monitors)` +
The default is: `wrap-around-the-workspace`

// end::body[]

include::util/man-footer.adoc[]
