= AeroSpace Commands
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: pygments
:toc: left

Commands listed in this file can be used in the config and CLI

'''

include::header.adoc[]

== close

----
close [-h|--help]
----

Closes the focused window

Normally, you don’t need to use this command, because macOS has its own
`+cmd+w+` binding. You might want to use the command from CLI for
scripting purposes

* Available since: 0.6.0-Beta

== close-all-windows-but-current

----
close-all-windows-but-current [-h|--help]
----

On the focused workspace, closes all windows but current.

== enable

----
enable [-h|--help] (on|off|toggle)
----

The command allows to temporarily disable window management

When you disable AeroSpace, windows from currently invisible workspaces
will be placed to the visible area of the screen

Key events are not intercepted when AeroSpace is disabled

* Available since: 0.5.0-Beta

== exec-and-forget

----
exec-and-forget [-h|--help] <bash-command>
----

Runs `+/bin/bash -c '$bash-command'+`. Stdout, stderr and exit code are
ignored.

For example, you can use this command to launch applications:
`+exec-and-forget open -n /System/Applications/Utilities/Terminal.app+`

== exec-and-wait

----
exec-and-wait [-h|--help] <bash-command>
----

Runs `+/bin/bash -c '$bash-command'+`, and waits until the command is
terminated. Stdout, stderr and exit code are ignored.

Please prefer `+exec-and-forget+`, unless you need to wait for the
termination.

You might want to wait for the termination if you have a list of
commands, and you want `+bash_command+` to exit until you run the next
command.

Suppose that you have this binding in your config:

[source,toml]
----
alt-enter = ['exec-and-wait open -n /System/Applications/Utilities/Terminal.app && sleep 1', 'layout floating']
----

It will open up Terminal.app and make it float. `+sleep 1+` is still
required because `+open+` returns before the window appears.

== flatten-workspace-tree

----
flatten-workspace-tree [-h|--help]
----

Flattens link:./guide.md#tree[the tree] of currently focused workspace.

The command is useful when you messed up with your layout, and it’s
easier to "`reset`" it and start again.

[#focus]
== focus

----
focus [-h|--help] (left|down|up|right)
----

Sets focus to the nearest window in link:./guide.md#tree[the tree] in
the given direction.

https://i3wm.org/docs/userguide.html#_focusing_moving_containers[Contrary
to i3], `+focus+` command doesn’t have a separate argument to focus
floating windows.From `+focus+` command perspective, floating windows
are part of link:./guide.md#tree[the tree].The floating window parent
container is determined as the smallest tiling container that contains
the center of the floating window.

This technique eliminates the need for an additional binding for
floating windows.

`+focus child|parent+`
https://github.com/nikitabobko/AeroSpace/issues/5[isn’t yet supported]
because the necessaty of this operation is under the question.

== fullscreen

----
fullscreen [-h|--help]
----

Toggles the fullscreen mode for the currently focused window.

Switching to a different window within the same workspace while the
current focused window is in fullscreen mode results in the fullscreen
window exiting fullscreen mode.

* Available since: 0.3.0-Beta

[#join-with]
== join-with

----
join-with [-h|--help] (left|down|up|right)
----

Puts the currently focused window and the nearest node in the specified
direction under a common parent container.

Given this layout

----
h_tiles
├── window 1
├── window 2 (focused)
└── window 3
----

`+join-with right+` will result in the following layout

----
h_tiles
├── window 1
└── v_tiles
    ├── window 2 (focused)
    └── window 3
----

NOTE: `+join-with+` is a high-level replacement for i3’s
https://i3wm.org/docs/userguide.html#_splitting_containers[split
command].There is an observation that the only reason why you might
want to split a node is to put several windows under a common
"`umbrella`" parent.Unlike `+split+`, `+join-with+` can be used with
xref:guide.adoc#normalization[enable-normalization-flatten-containers]

[#layout]
== layout

----
layout [-h|--help] (h_tiles|v_tiles|h_accordion|v_accordion|tiles|accordion|horizontal|vertical|tiling|floating)...
----

Changes layout of the focused window to the given layout.

If several layouts are supplied then finds the first layout that doesn’t
describe the currently active layout, and applies the found layout.

`+tiling+` is the only argument that makes the focused floating window
tiled.

== mode

----
mode [-h|--help] <target-mode>
----

Activates the specified xref:guide.adoc#binding-modes[binding mode]

[#move-node-to-workspace]
== move-node-to-workspace

----
move-node-to-workspace [-h|--help] <target-workspace-name>
----

Moves currently focused window to the specified workspace

[#move-through]
== move-through

----
move-through [-h|--help] (left|down|up|right) [floating_pixel]
----

Moves the window in the given direction.The optional `+floating_pixel+`
argument specifies how far the window should be moved if it is floating.
The default is 50 pixels

NOTE: This command is an analog of https://i3wm.org/docs/userguide.html#move_direction[i3’s move command]

*Example 1*

Given this layout

----
h_tiles
├── window 1 (focused)
└── window 2
----

`+move-through right+` will result in the following layout

----
h_tiles
├── window 2
└── window 1 (focused)
----

*Example 2*

Given this layout

----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----

`+move-through right+` will result in the following layout

----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----

*Example 3*

Given this layout

----
h_tiles
├── window 1
└── v_tiles
    ├── window 3
    ├── window 2 (focused)
    └── window 4
----

`+move-through left+` will result in the following layout

----
h_tiles
├── window 1
├── window 2 (focused)
└── v_tiles
    ├── window 3
    └── window 4
----

*Implicit container example*

In some cases, `+move-through+` needs to implicitly create a container
to fullfill your command.

Given this layout

----
h_tiles
├── window 1
├── window 2 (focused)
└── window 3
----

`+move-through up+` will result in the following layout

----
v_tiles
├── window 2 (focused)
└── h_tiles
    ├── window 1
    └── window 3
----

`+v_tiles+` is an implicitly created container.

[#move-workspace-to-monitor]
== move-workspace-to-monitor

----
move-workspace-to-monitor (next|prev)
----

Moves currently focused workspace to the next or previous monitor

The command doesn’t have effect on workspaces
link:./guide.md#assign-workspaces-to-monitors[that have monitor
assignment]

* Deprecated name: `+move-workspace-to-display+`

== reload-config

----
reload-config [-h|--help]
----

Reloads currently active config.

== resize

----
resize [-h|--help] (smart|width|height) [+|-]number
----

Resizes the currently active window

The dimension to resize is chosen by the first argument

* `+width+` changes width
* `+height+` changes height
* `+smart+` changes width if the parent has horizontal orientation, and
it changes height if the parent has vertical orientation

Second argument controls how much the size is changes

* If the `+number+` is prefixed with `+++` then the dimension is
increased
* If the `+number+` is prefixed with `+-+` then the dimension is
decreased
* If the `+number+` is prefixed with neither `+++` nor `+-+` then the
command changes the absolute value of the dimension

[#split]
== split

----
split [-h|--help] (horizontal|vertical|opposite)
----

*If the parent of currently focused window contains more than one
child*, then the command

[arabic]
. Creates a new tiling container
. Replaces currently focused window with the container
. Puts the currently focused window into the container as its the only
child

The argument configures orientation of the newly created container.
`+opposite+` means opposite orientation compared to the parent
container.

*If the parent of currently focused window contains only a single child*
(the window itself), then `+split+` command changes the orientation of
the parent container

IMPORTANT: `+split+` command does nothing if `+enable-normalization-flatten-containers+` is turned on.
Consider using `+join-with+` if you want to keep `+enable-normalization-flatten-containers+` enabled

* Available since: 0.3.0-Beta

== workspace-back-and-forth

----
workspace-back-and-forth [-h|--help]
----

Switches between currently focused workspace and previously focused
workspace back and forth.

[#workspace]
== workspace

----
workspace [-h|--help] <target-workspace-name>
----

Activates the specified workspace
