import AppKit
import Common
import Carbon

func getKeyMapPreset(_ layout: KeyMapping.Preset) -> [String: UInt32] {
    return switch layout {
        case .qwerty: qwertyKeyMap
        case .dvorak: dvorakKeyMap
        case .colemak: colemakKeyMap
    }
}

let keyNotationToKeyCode = qwertyKeyMap

private let qwertyKeyMap = [
    "sectionSign": kVK_ISO_Section,
    "0": kVK_ANSI_0,
    "1": kVK_ANSI_1,
    "2": kVK_ANSI_2,
    "3": kVK_ANSI_3,
    "4": kVK_ANSI_4,
    "5": kVK_ANSI_5,
    "6": kVK_ANSI_6,
    "7": kVK_ANSI_7,
    "8": kVK_ANSI_8,
    "9": kVK_ANSI_9,
    "minus": kVK_ANSI_Minus,
    "equal": kVK_ANSI_Equal,

    "q": kVK_ANSI_Q,
    "w": kVK_ANSI_W,
    "e": kVK_ANSI_E,
    "r": kVK_ANSI_R,
    "t": kVK_ANSI_T,
    "y": kVK_ANSI_Y,
    "u": kVK_ANSI_U,
    "i": kVK_ANSI_I,
    "o": kVK_ANSI_O,
    "p": kVK_ANSI_P,
    "leftSquareBracket": kVK_ANSI_LeftBracket,
    "rightSquareBracket": kVK_ANSI_RightBracket,
    "backslash": kVK_ANSI_Backslash,

    "a": kVK_ANSI_A,
    "s": kVK_ANSI_S,
    "d": kVK_ANSI_D,
    "f": kVK_ANSI_F,
    "g": kVK_ANSI_G,
    "h": kVK_ANSI_H,
    "j": kVK_ANSI_J,
    "k": kVK_ANSI_K,
    "l": kVK_ANSI_L,
    "semicolon": kVK_ANSI_Semicolon,
    "quote": kVK_ANSI_Quote,

    "z": kVK_ANSI_Z,
    "x": kVK_ANSI_X,
    "c": kVK_ANSI_C,
    "v": kVK_ANSI_V,
    "b": kVK_ANSI_B,
    "n": kVK_ANSI_N,
    "m": kVK_ANSI_M,
    "comma": kVK_ANSI_Comma,
    "period": kVK_ANSI_Period,
    "slash": kVK_ANSI_Slash,

    "keypad0": kVK_ANSI_Keypad0,
    "keypad1": kVK_ANSI_Keypad1,
    "keypad2": kVK_ANSI_Keypad2,
    "keypad3": kVK_ANSI_Keypad3,
    "keypad4": kVK_ANSI_Keypad4,
    "keypad5": kVK_ANSI_Keypad5,
    "keypad6": kVK_ANSI_Keypad6,
    "keypad7": kVK_ANSI_Keypad7,
    "keypad8": kVK_ANSI_Keypad8,
    "keypad9": kVK_ANSI_Keypad9,
    "keypadClear": kVK_ANSI_KeypadClear,
    "keypadDecimalMark": kVK_ANSI_KeypadDecimal,
    "keypadDivide": kVK_ANSI_KeypadDivide,
    "keypadEnter": kVK_ANSI_KeypadEnter,
    "keypadEqual": kVK_ANSI_KeypadEquals,
    "keypadMinus": kVK_ANSI_KeypadMinus,
    "keypadMultiply": kVK_ANSI_KeypadMultiply,
    "keypadPlus": kVK_ANSI_KeypadPlus,

    "pageUp": kVK_PageUp,
    "pageDown": kVK_PageDown,
    "home": kVK_Home,
    "end": kVK_End,
    "forwardDelete": kVK_ForwardDelete,

    "f1": kVK_F1,
    "f2": kVK_F2,
    "f3": kVK_F3,
    "f4": kVK_F4,
    "f5": kVK_F5,
    "f6": kVK_F6,
    "f7": kVK_F7,
    "f8": kVK_F8,
    "f9": kVK_F9,
    "f10": kVK_F10,
    "f11": kVK_F11,
    "f12": kVK_F12,
    "f13": kVK_F13,
    "f14": kVK_F14,
    "f15": kVK_F15,
    "f16": kVK_F16,
    "f17": kVK_F17,
    "f18": kVK_F18,
    "f19": kVK_F19,
    "f20": kVK_F20,

    "backtick": kVK_ANSI_Grave,
    "space": kVK_Space,
    "enter": kVK_Return,
    "esc": kVK_Escape,
    "backspace": kVK_Delete,
    "tab": kVK_Tab,

    "left": kVK_LeftArrow,
    "down": kVK_DownArrow,
    "up": kVK_UpArrow,
    "right": kVK_RightArrow,
].mapValues(UInt32.init)

private let dvorakKeyMap: [String: UInt32] = qwertyKeyMap + [
    "leftSquareBracket": kVK_ANSI_Minus,
    "rightSquareBracket": kVK_ANSI_Equal,

    "quote": kVK_ANSI_Q,
    "comma": kVK_ANSI_W,
    "period": kVK_ANSI_E,
    "p": kVK_ANSI_R,
    "y": kVK_ANSI_T,
    "f": kVK_ANSI_Y,
    "g": kVK_ANSI_U,
    "c": kVK_ANSI_I,
    "r": kVK_ANSI_O,
    "l": kVK_ANSI_P,
    "slash": kVK_ANSI_LeftBracket,
    "equal": kVK_ANSI_RightBracket,
    // backslash remains backslash

    "a": kVK_ANSI_A, // explicit for clarity
    "o": kVK_ANSI_S,
    "e": kVK_ANSI_D,
    "u": kVK_ANSI_F,
    "i": kVK_ANSI_G,
    "d": kVK_ANSI_H,
    "h": kVK_ANSI_J,
    "t": kVK_ANSI_K,
    "n": kVK_ANSI_L,
    "s": kVK_ANSI_Semicolon,
    "minus": kVK_ANSI_Quote,

    "semicolon": kVK_ANSI_Z,
    "q": kVK_ANSI_X,
    "j": kVK_ANSI_C,
    "k": kVK_ANSI_V,
    "x": kVK_ANSI_B,
    "b": kVK_ANSI_N,
    "m": kVK_ANSI_M,
    "w": kVK_ANSI_Comma,
    "v": kVK_ANSI_Period,
    "z": kVK_ANSI_Slash,
].mapValues(UInt32.init)

private let colemakKeyMap: [String: UInt32] = qwertyKeyMap + [
    "q": kVK_ANSI_Q,
    "w": kVK_ANSI_W,
    "f": kVK_ANSI_E,
    "p": kVK_ANSI_R,
    "g": kVK_ANSI_T,
    "j": kVK_ANSI_Y,
    "l": kVK_ANSI_U,
    "u": kVK_ANSI_I,
    "y": kVK_ANSI_O,
    "semicolon": kVK_ANSI_P,

    "a": kVK_ANSI_A,
    "r": kVK_ANSI_S,
    "s": kVK_ANSI_D,
    "t": kVK_ANSI_F,
    "d": kVK_ANSI_G,
    "h": kVK_ANSI_H,
    "n": kVK_ANSI_J,
    "e": kVK_ANSI_K,
    "i": kVK_ANSI_L,
    "o": kVK_ANSI_Semicolon,

    "z": kVK_ANSI_Z,
    "x": kVK_ANSI_X,
    "c": kVK_ANSI_C,
    "v": kVK_ANSI_V,
    "b": kVK_ANSI_B,
    "k": kVK_ANSI_N,
    "m": kVK_ANSI_M,
].mapValues(UInt32.init)
